### ISSUE TITLE
关于接受信息

### ISSUE THREAD

**Issue by DMPico** [dong9205/wechat_hook#1]
您好，

对您的项目非常感兴趣，想聊一下除了发送信息，采用您的方式可以接受信息嘛？

比如，一个典型的使用案例是接受到微信的信息之后将其在Python端存为String，供其他函数或方法使用？

谢谢

**Comment by dong9205** [comment]
@DMPico 感谢你能关注到这个项目，这个项目我做的比较简单，只是做了一层HTTP发送消息封装， 底层调用的是**github.com/eatmoreapple/openwechat**这个项目的接口.

你这个需求肯定是可以实现的，关于接收消息的更多信息, **我推荐你可以参考文档 https://openwechat.readthedocs.io/zh/latest/message.html#id2** ，如果你看完之后没有思路，可以再联系我，我可以再进一步帮助你.

**Comment by DMPico** [comment]
@dong9205 你好，感谢及时回复，我去参考一下你推荐的文档。

谢谢！
